---

repo_url: https://github.com/rustprooflabs/piws.git
repo_branch: master
repo_path: /srv/piws
venv_path: /srv/piws_venv

piws_db_name: piws
piws_db_user: piws
piws_db_ip: 127.0.0.1

python_version: python3.7

repo_url_pgdd: https://github.com/rustprooflabs/pgdd.git
repo_branch_pgdd: master
repo_path_pgdd: /srv/pgdd

piws_db_password: SecurePassword

...