---

pg_version: 14

pg_wal_level: minimal
pg_max_wal_senders: 0
pg_hot_standby: off

pg_checkpoint_timeout: 60min
pg_checkpoint_completion_target: 0.9
pg_max_wal_size: 512MB
pg_min_wal_size: 80MB
pg_shared_buffers: 50MB

...