---

pg_version: 9.6

pg_wal_level: hot_standby
pg_max_wal_senders: 2
pg_wal_keep_segments: 16
pg_hot_standby: on

pg_checkpoint_timeout: 30min   # range 30s-1d
pg_max_wal_size: 512MB
pg_min_wal_size: 80MB
pg_shared_buffers: 50MB

...